# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/bytetrack_tracker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dproto/bytetrack_tracker.proto\x12\tbytetrack\x1a\x1bgoogle/protobuf/empty.proto\"f\n\rTrackerConfig\x12\x14\n\x0ctrack_thresh\x18\x01 \x01(\x02\x12\x13\n\x0bhigh_thresh\x18\x02 \x01(\x02\x12\x14\n\x0cmatch_thresh\x18\x03 \x01(\x02\x12\x14\n\x0ctrack_buffer\x18\x04 \x01(\x05\"7\n\x0bInitRequest\x12(\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x18.bytetrack.TrackerConfig\"\x1f\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"h\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\r\n\x05width\x18\x05 \x01(\x02\x12\x0e\n\x06height\x18\x06 \x01(\x02\";\n\x0f\x44\x65tectionResult\x12(\n\ndetections\x18\x01 \x03(\x0b\x32\x14.bytetrack.Detection\"x\n\rTrackedObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\"N\n\rUpdateRequest\x12\r\n\x05\x66rame\x18\x01 \x01(\x0c\x12.\n\ndet_result\x18\x02 \x01(\x0b\x32\x1a.bytetrack.DetectionResult\":\n\x0eUpdateResponse\x12(\n\x06tracks\x18\x01 \x03(\x0b\x32\x18.bytetrack.TrackedObject\"*\n\x16\x42ufferCapacityResponse\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\x32\x93\x02\n\x10\x42yteTrackService\x12\x37\n\x04Init\x12\x16.bytetrack.InitRequest\x1a\x17.bytetrack.InitResponse\x12=\n\x06Update\x12\x18.bytetrack.UpdateRequest\x1a\x19.bytetrack.UpdateResponse\x12\x37\n\x05\x43lose\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12N\n\x11GetBufferCapacity\x12\x16.google.protobuf.Empty\x1a!.bytetrack.BufferCapacityResponseB+\n\x16knu.app.grpc.bytetrackB\x0f\x42yteTrackProtosP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.bytetrack_tracker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026knu.app.grpc.bytetrackB\017ByteTrackProtosP\001'
  _globals['_TRACKERCONFIG']._serialized_start=73
  _globals['_TRACKERCONFIG']._serialized_end=175
  _globals['_INITREQUEST']._serialized_start=177
  _globals['_INITREQUEST']._serialized_end=232
  _globals['_INITRESPONSE']._serialized_start=234
  _globals['_INITRESPONSE']._serialized_end=265
  _globals['_DETECTION']._serialized_start=267
  _globals['_DETECTION']._serialized_end=371
  _globals['_DETECTIONRESULT']._serialized_start=373
  _globals['_DETECTIONRESULT']._serialized_end=432
  _globals['_TRACKEDOBJECT']._serialized_start=434
  _globals['_TRACKEDOBJECT']._serialized_end=554
  _globals['_UPDATEREQUEST']._serialized_start=556
  _globals['_UPDATEREQUEST']._serialized_end=634
  _globals['_UPDATERESPONSE']._serialized_start=636
  _globals['_UPDATERESPONSE']._serialized_end=694
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_start=696
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_end=738
  _globals['_BYTETRACKSERVICE']._serialized_start=741
  _globals['_BYTETRACKSERVICE']._serialized_end=1016
# @@protoc_insertion_point(module_scope)
