# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import bytetrack_tracker_pb2 as proto_dot_bytetrack__tracker__pb2


class ByteTrackServiceStub(object):
    """========================
    SERVICE
    ========================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/bytetrack.ByteTrackService/Init',
                request_serializer=proto_dot_bytetrack__tracker__pb2.InitRequest.SerializeToString,
                response_deserializer=proto_dot_bytetrack__tracker__pb2.InitResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/bytetrack.ByteTrackService/Update',
                request_serializer=proto_dot_bytetrack__tracker__pb2.UpdateRequest.SerializeToString,
                response_deserializer=proto_dot_bytetrack__tracker__pb2.UpdateResponse.FromString,
                )
        self.Close = channel.unary_unary(
                '/bytetrack.ByteTrackService/Close',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetBufferCapacity = channel.unary_unary(
                '/bytetrack.ByteTrackService/GetBufferCapacity',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_bytetrack__tracker__pb2.BufferCapacityResponse.FromString,
                )


class ByteTrackServiceServicer(object):
    """========================
    SERVICE
    ========================
    """

    def Init(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBufferCapacity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ByteTrackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=proto_dot_bytetrack__tracker__pb2.InitRequest.FromString,
                    response_serializer=proto_dot_bytetrack__tracker__pb2.InitResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=proto_dot_bytetrack__tracker__pb2.UpdateRequest.FromString,
                    response_serializer=proto_dot_bytetrack__tracker__pb2.UpdateResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBufferCapacity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBufferCapacity,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_bytetrack__tracker__pb2.BufferCapacityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bytetrack.ByteTrackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ByteTrackService(object):
    """========================
    SERVICE
    ========================
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bytetrack.ByteTrackService/Init',
            proto_dot_bytetrack__tracker__pb2.InitRequest.SerializeToString,
            proto_dot_bytetrack__tracker__pb2.InitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bytetrack.ByteTrackService/Update',
            proto_dot_bytetrack__tracker__pb2.UpdateRequest.SerializeToString,
            proto_dot_bytetrack__tracker__pb2.UpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bytetrack.ByteTrackService/Close',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBufferCapacity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bytetrack.ByteTrackService/GetBufferCapacity',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_bytetrack__tracker__pb2.BufferCapacityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
