# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sort_tracker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/sort_tracker.proto\x12\x0ctracker.sort\x1a\x1bgoogle/protobuf/empty.proto\"\x91\x01\n\rTrackerConfig\x12\x19\n\x11lost_track_buffer\x18\x01 \x01(\x05\x12\"\n\x1atrack_activation_threshold\x18\x02 \x01(\x02\x12\"\n\x1aminimum_consecutive_frames\x18\x03 \x01(\x05\x12\x1d\n\x15minimum_iou_threshold\x18\x04 \x01(\x02\"J\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12+\n\ndetections\x18\x02 \x03(\x0b\x32\x17.tracker.sort.Detection\"h\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nclass_name\x18\x06 \x01(\t\"\x8a\x01\n\rTrackedObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\x05\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\t\n\x01x\x18\x05 \x01(\x02\x12\t\n\x01y\x18\x06 \x01(\x02\x12\r\n\x05width\x18\x07 \x01(\x02\x12\x0e\n\x06height\x18\x08 \x01(\x02\"\x1f\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"=\n\x0eUpdateResponse\x12+\n\x06tracks\x18\x01 \x03(\x0b\x32\x1b.tracker.sort.TrackedObject\"*\n\x16\x42ufferCapacityResponse\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t2\xe9\x02\n\x0bSortService\x12?\n\x04Init\x12\x1b.tracker.sort.TrackerConfig\x1a\x1a.tracker.sort.InitResponse\x12\x42\n\x06Update\x12\x1a.tracker.sort.FrameRequest\x1a\x1c.tracker.sort.UpdateResponse\x12=\n\x05\x43lose\x12\x1c.tracker.sort.SessionRequest\x1a\x16.google.protobuf.Empty\x12W\n\x11GetBufferCapacity\x12\x1c.tracker.sort.SessionRequest\x1a$.tracker.sort.BufferCapacityResponse\x12=\n\x05\x43lear\x12\x1c.tracker.sort.SessionRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sort_tracker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACKERCONFIG']._serialized_start=72
  _globals['_TRACKERCONFIG']._serialized_end=217
  _globals['_FRAMEREQUEST']._serialized_start=219
  _globals['_FRAMEREQUEST']._serialized_end=293
  _globals['_DETECTION']._serialized_start=295
  _globals['_DETECTION']._serialized_end=399
  _globals['_TRACKEDOBJECT']._serialized_start=402
  _globals['_TRACKEDOBJECT']._serialized_end=540
  _globals['_INITRESPONSE']._serialized_start=542
  _globals['_INITRESPONSE']._serialized_end=573
  _globals['_UPDATERESPONSE']._serialized_start=575
  _globals['_UPDATERESPONSE']._serialized_end=636
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_start=638
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_end=680
  _globals['_SESSIONREQUEST']._serialized_start=682
  _globals['_SESSIONREQUEST']._serialized_end=718
  _globals['_SORTSERVICE']._serialized_start=721
  _globals['_SORTSERVICE']._serialized_end=1082
# @@protoc_insertion_point(module_scope)
