# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import ssd_detector_pb2 as proto_dot_ssd__detector__pb2


class SsdDetectionServiceStub(object):
    """=======================================
    SERVICE
    =======================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.unary_unary(
                '/ssd.detector.SsdDetectionService/SetConfig',
                request_serializer=proto_dot_ssd__detector__pb2.SsdConfig.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/ssd.detector.SsdDetectionService/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_ssd__detector__pb2.GetConfigResponse.FromString,
                )
        self.StartStreaming = channel.unary_unary(
                '/ssd.detector.SsdDetectionService/StartStreaming',
                request_serializer=proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
                response_deserializer=proto_dot_ssd__detector__pb2.StreamStatus.FromString,
                )
        self.StopStreaming = channel.unary_unary(
                '/ssd.detector.SsdDetectionService/StopStreaming',
                request_serializer=proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
                response_deserializer=proto_dot_ssd__detector__pb2.StreamStatus.FromString,
                )
        self.RestartConnection = channel.unary_unary(
                '/ssd.detector.SsdDetectionService/RestartConnection',
                request_serializer=proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
                response_deserializer=proto_dot_ssd__detector__pb2.StreamStatus.FromString,
                )
        self.StreamDetect = channel.stream_stream(
                '/ssd.detector.SsdDetectionService/StreamDetect',
                request_serializer=proto_dot_ssd__detector__pb2.FrameRequest.SerializeToString,
                response_deserializer=proto_dot_ssd__detector__pb2.TrackingResult.FromString,
                )


class SsdDetectionServiceServicer(object):
    """=======================================
    SERVICE
    =======================================

    """

    def SetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDetect(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SsdDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=proto_dot_ssd__detector__pb2.SsdConfig.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_ssd__detector__pb2.GetConfigResponse.SerializeToString,
            ),
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=proto_dot_ssd__detector__pb2.SessionRequest.FromString,
                    response_serializer=proto_dot_ssd__detector__pb2.StreamStatus.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=proto_dot_ssd__detector__pb2.SessionRequest.FromString,
                    response_serializer=proto_dot_ssd__detector__pb2.StreamStatus.SerializeToString,
            ),
            'RestartConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartConnection,
                    request_deserializer=proto_dot_ssd__detector__pb2.SessionRequest.FromString,
                    response_serializer=proto_dot_ssd__detector__pb2.StreamStatus.SerializeToString,
            ),
            'StreamDetect': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDetect,
                    request_deserializer=proto_dot_ssd__detector__pb2.FrameRequest.FromString,
                    response_serializer=proto_dot_ssd__detector__pb2.TrackingResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ssd.detector.SsdDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SsdDetectionService(object):
    """=======================================
    SERVICE
    =======================================

    """

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssd.detector.SsdDetectionService/SetConfig',
            proto_dot_ssd__detector__pb2.SsdConfig.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssd.detector.SsdDetectionService/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_ssd__detector__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssd.detector.SsdDetectionService/StartStreaming',
            proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
            proto_dot_ssd__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssd.detector.SsdDetectionService/StopStreaming',
            proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
            proto_dot_ssd__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ssd.detector.SsdDetectionService/RestartConnection',
            proto_dot_ssd__detector__pb2.SessionRequest.SerializeToString,
            proto_dot_ssd__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamDetect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/ssd.detector.SsdDetectionService/StreamDetect',
            proto_dot_ssd__detector__pb2.FrameRequest.SerializeToString,
            proto_dot_ssd__detector__pb2.TrackingResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
