# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ssd_detector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/ssd_detector.proto\x12\x0cssd.detector\x1a\x1bgoogle/protobuf/empty.proto\"\x97\x01\n\tSsdConfig\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x13\n\x0binput_width\x18\x02 \x01(\x05\x12\x14\n\x0cinput_height\x18\x03 \x01(\x05\x12\x1c\n\x14\x63onfidence_threshold\x18\x04 \x01(\x02\x12\x15\n\rnms_threshold\x18\x05 \x01(\x02\x12\x16\n\x0emax_detections\x18\x06 \x01(\x05\"<\n\x11GetConfigResponse\x12\'\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x17.ssd.detector.SsdConfig\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"0\n\x0cStreamStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"D\n\x0c\x46rameRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"z\n\tDetection\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\"P\n\x0eTrackingResult\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12+\n\ndetections\x18\x02 \x03(\x0b\x32\x17.ssd.detector.Detection2\xcd\x03\n\x13SsdDetectionService\x12<\n\tSetConfig\x12\x17.ssd.detector.SsdConfig\x1a\x16.google.protobuf.Empty\x12\x44\n\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x1f.ssd.detector.GetConfigResponse\x12J\n\x0eStartStreaming\x12\x1c.ssd.detector.SessionRequest\x1a\x1a.ssd.detector.StreamStatus\x12I\n\rStopStreaming\x12\x1c.ssd.detector.SessionRequest\x1a\x1a.ssd.detector.StreamStatus\x12M\n\x11RestartConnection\x12\x1c.ssd.detector.SessionRequest\x1a\x1a.ssd.detector.StreamStatus\x12L\n\x0cStreamDetect\x12\x1a.ssd.detector.FrameRequest\x1a\x1c.ssd.detector.TrackingResult(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ssd_detector_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SSDCONFIG']._serialized_start=72
  _globals['_SSDCONFIG']._serialized_end=223
  _globals['_GETCONFIGRESPONSE']._serialized_start=225
  _globals['_GETCONFIGRESPONSE']._serialized_end=285
  _globals['_SESSIONREQUEST']._serialized_start=287
  _globals['_SESSIONREQUEST']._serialized_end=323
  _globals['_STREAMSTATUS']._serialized_start=325
  _globals['_STREAMSTATUS']._serialized_end=373
  _globals['_FRAMEREQUEST']._serialized_start=375
  _globals['_FRAMEREQUEST']._serialized_end=443
  _globals['_DETECTION']._serialized_start=445
  _globals['_DETECTION']._serialized_end=567
  _globals['_TRACKINGRESULT']._serialized_start=569
  _globals['_TRACKINGRESULT']._serialized_end=649
  _globals['_SSDDETECTIONSERVICE']._serialized_start=652
  _globals['_SSDDETECTIONSERVICE']._serialized_end=1113
# @@protoc_insertion_point(module_scope)
