# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/strongsort_tracker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eproto/strongsort_tracker.proto\x12\x12tracker.strongsort\x1a\x1bgoogle/protobuf/empty.proto\"\x8b\x01\n\rTrackerConfig\x12\x0f\n\x07max_age\x18\x01 \x01(\x05\x12\x10\n\x08min_hits\x18\x02 \x01(\x05\x12\x15\n\riou_threshold\x18\x03 \x01(\x02\x12\x1b\n\x13max_cosine_distance\x18\x04 \x01(\x02\x12\x11\n\tnn_budget\x18\x05 \x01(\x05\x12\x10\n\x08use_reid\x18\x06 \x01(\x08\"P\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x31\n\ndetections\x18\x02 \x03(\x0b\x32\x1d.tracker.strongsort.Detection\"h\n\tDetection\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\x12\x12\n\nconfidence\x18\x05 \x01(\x02\x12\x12\n\nclass_name\x18\x06 \x01(\t\"\x8a\x01\n\rTrackedObject\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x10\n\x08\x63lass_id\x18\x03 \x01(\x05\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12\t\n\x01x\x18\x05 \x01(\x02\x12\t\n\x01y\x18\x06 \x01(\x02\x12\r\n\x05width\x18\x07 \x01(\x02\x12\x0e\n\x06height\x18\x08 \x01(\x02\"\x1f\n\x0cInitResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"C\n\x0eUpdateResponse\x12\x31\n\x06tracks\x18\x01 \x03(\x0b\x32!.tracker.strongsort.TrackedObject\"*\n\x16\x42ufferCapacityResponse\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\"$\n\x0eSessionRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t2\x9f\x03\n\x11StrongSortService\x12K\n\x04Init\x12!.tracker.strongsort.TrackerConfig\x1a .tracker.strongsort.InitResponse\x12N\n\x06Update\x12 .tracker.strongsort.FrameRequest\x1a\".tracker.strongsort.UpdateResponse\x12\x43\n\x05\x43lose\x12\".tracker.strongsort.SessionRequest\x1a\x16.google.protobuf.Empty\x12\x63\n\x11GetBufferCapacity\x12\".tracker.strongsort.SessionRequest\x1a*.tracker.strongsort.BufferCapacityResponse\x12\x43\n\x05\x43lear\x12\".tracker.strongsort.SessionRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.strongsort_tracker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TRACKERCONFIG']._serialized_start=84
  _globals['_TRACKERCONFIG']._serialized_end=223
  _globals['_FRAMEREQUEST']._serialized_start=225
  _globals['_FRAMEREQUEST']._serialized_end=305
  _globals['_DETECTION']._serialized_start=307
  _globals['_DETECTION']._serialized_end=411
  _globals['_TRACKEDOBJECT']._serialized_start=414
  _globals['_TRACKEDOBJECT']._serialized_end=552
  _globals['_INITRESPONSE']._serialized_start=554
  _globals['_INITRESPONSE']._serialized_end=585
  _globals['_UPDATERESPONSE']._serialized_start=587
  _globals['_UPDATERESPONSE']._serialized_end=654
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_start=656
  _globals['_BUFFERCAPACITYRESPONSE']._serialized_end=698
  _globals['_SESSIONREQUEST']._serialized_start=700
  _globals['_SESSIONREQUEST']._serialized_end=736
  _globals['_STRONGSORTSERVICE']._serialized_start=739
  _globals['_STRONGSORTSERVICE']._serialized_end=1154
# @@protoc_insertion_point(module_scope)
