# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import yolo_detector_pb2 as proto_dot_yolo__detector__pb2


class YoloDetectionServiceStub(object):
    """========================
    SERVICE
    ========================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetConfig = channel.unary_unary(
                '/yolo.YoloDetectionService/SetConfig',
                request_serializer=proto_dot_yolo__detector__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.GetConfig = channel.unary_unary(
                '/yolo.YoloDetectionService/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_yolo__detector__pb2.GetConfigResponse.FromString,
                )
        self.StartStreaming = channel.unary_unary(
                '/yolo.YoloDetectionService/StartStreaming',
                request_serializer=proto_dot_yolo__detector__pb2.StartStreamingRequest.SerializeToString,
                response_deserializer=proto_dot_yolo__detector__pb2.StreamStatus.FromString,
                )
        self.StopStreaming = channel.unary_unary(
                '/yolo.YoloDetectionService/StopStreaming',
                request_serializer=proto_dot_yolo__detector__pb2.StopStreamingRequest.SerializeToString,
                response_deserializer=proto_dot_yolo__detector__pb2.StreamStatus.FromString,
                )
        self.RestartConnection = channel.unary_unary(
                '/yolo.YoloDetectionService/RestartConnection',
                request_serializer=proto_dot_yolo__detector__pb2.RestartConnectionRequest.SerializeToString,
                response_deserializer=proto_dot_yolo__detector__pb2.StreamStatus.FromString,
                )
        self.StreamTrack = channel.stream_stream(
                '/yolo.YoloDetectionService/StreamTrack',
                request_serializer=proto_dot_yolo__detector__pb2.ImageFrame.SerializeToString,
                response_deserializer=proto_dot_yolo__detector__pb2.TrackingResult.FromString,
                )


class YoloDetectionServiceServicer(object):
    """========================
    SERVICE
    ========================

    """

    def SetConfig(self, request, context):
        """--- CONFIG MANAGEMENT ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartStreaming(self, request, context):
        """--- STREAM CONTROL ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopStreaming(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestartConnection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrack(self, request_iterator, context):
        """--- IMAGE STREAM ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YoloDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=proto_dot_yolo__detector__pb2.SetConfigRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_yolo__detector__pb2.GetConfigResponse.SerializeToString,
            ),
            'StartStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StartStreaming,
                    request_deserializer=proto_dot_yolo__detector__pb2.StartStreamingRequest.FromString,
                    response_serializer=proto_dot_yolo__detector__pb2.StreamStatus.SerializeToString,
            ),
            'StopStreaming': grpc.unary_unary_rpc_method_handler(
                    servicer.StopStreaming,
                    request_deserializer=proto_dot_yolo__detector__pb2.StopStreamingRequest.FromString,
                    response_serializer=proto_dot_yolo__detector__pb2.StreamStatus.SerializeToString,
            ),
            'RestartConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.RestartConnection,
                    request_deserializer=proto_dot_yolo__detector__pb2.RestartConnectionRequest.FromString,
                    response_serializer=proto_dot_yolo__detector__pb2.StreamStatus.SerializeToString,
            ),
            'StreamTrack': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTrack,
                    request_deserializer=proto_dot_yolo__detector__pb2.ImageFrame.FromString,
                    response_serializer=proto_dot_yolo__detector__pb2.TrackingResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yolo.YoloDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YoloDetectionService(object):
    """========================
    SERVICE
    ========================

    """

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolo.YoloDetectionService/SetConfig',
            proto_dot_yolo__detector__pb2.SetConfigRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolo.YoloDetectionService/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_yolo__detector__pb2.GetConfigResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolo.YoloDetectionService/StartStreaming',
            proto_dot_yolo__detector__pb2.StartStreamingRequest.SerializeToString,
            proto_dot_yolo__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopStreaming(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolo.YoloDetectionService/StopStreaming',
            proto_dot_yolo__detector__pb2.StopStreamingRequest.SerializeToString,
            proto_dot_yolo__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RestartConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yolo.YoloDetectionService/RestartConnection',
            proto_dot_yolo__detector__pb2.RestartConnectionRequest.SerializeToString,
            proto_dot_yolo__detector__pb2.StreamStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamTrack(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/yolo.YoloDetectionService/StreamTrack',
            proto_dot_yolo__detector__pb2.ImageFrame.SerializeToString,
            proto_dot_yolo__detector__pb2.TrackingResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
