# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: yolo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'yolo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nyolo.proto\x12\x04yolo\"\xeb\x01\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x16\n\x0e\x63onf_threshold\x18\x02 \x01(\x02\x12\x15\n\riou_threshold\x18\x03 \x01(\x02\x12\x0f\n\x07\x63lasses\x18\x04 \x03(\t\x12\x0f\n\x07max_det\x18\x05 \x01(\x05\x12\x0f\n\x07\x61ugment\x18\x06 \x01(\x08\x12\x13\n\x0bmulti_label\x18\x07 \x01(\x08\x12\x14\n\x0c\x61gnostic_nms\x18\x08 \x01(\x08\x12\x10\n\x08img_size\x18\t \x01(\x05\x12\x0c\n\x04half\x18\n \x01(\x08\x12\x0e\n\x06\x64\x65vice\x18\x0b \x01(\t\x12\x0f\n\x07weights\x18\x0c \x01(\t\"j\n\x0b\x42oundingBox\x12\x12\n\nclass_name\x18\x01 \x01(\t\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\r\n\x05width\x18\x04 \x01(\x02\x12\x0e\n\x06height\x18\x05 \x01(\x02\x12\x12\n\nconfidence\x18\x06 \x01(\x02\"1\n\rImageResponse\x12 \n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x11.yolo.BoundingBox2G\n\x0bYoloService\x12\x38\n\rDetectObjects\x12\x12.yolo.ImageRequest\x1a\x13.yolo.ImageResponseB\x1f\n\x10\x63om.example.yoloB\tYoloProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yolo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\020com.example.yoloB\tYoloProtoP\001'
  _globals['_IMAGEREQUEST']._serialized_start=21
  _globals['_IMAGEREQUEST']._serialized_end=256
  _globals['_BOUNDINGBOX']._serialized_start=258
  _globals['_BOUNDINGBOX']._serialized_end=364
  _globals['_IMAGERESPONSE']._serialized_start=366
  _globals['_IMAGERESPONSE']._serialized_end=415
  _globals['_YOLOSERVICE']._serialized_start=417
  _globals['_YOLOSERVICE']._serialized_end=488
# @@protoc_insertion_point(module_scope)
