# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import bytetrack_objecttracker_pb2 as proto_dot_bytetrack__objecttracker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/bytetrack_objecttracker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TrackerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitTracker = channel.unary_unary(
                '/tracker.TrackerService/InitTracker',
                request_serializer=proto_dot_bytetrack__objecttracker__pb2.TrackerParams.SerializeToString,
                response_deserializer=proto_dot_bytetrack__objecttracker__pb2.InitResponse.FromString,
                _registered_method=True)
        self.UpdateTracks = channel.unary_unary(
                '/tracker.TrackerService/UpdateTracks',
                request_serializer=proto_dot_bytetrack__objecttracker__pb2.FrameDetections.SerializeToString,
                response_deserializer=proto_dot_bytetrack__objecttracker__pb2.TracksResponse.FromString,
                _registered_method=True)


class TrackerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitTracker(self, request, context):
        """новый метод
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTracks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrackerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitTracker': grpc.unary_unary_rpc_method_handler(
                    servicer.InitTracker,
                    request_deserializer=proto_dot_bytetrack__objecttracker__pb2.TrackerParams.FromString,
                    response_serializer=proto_dot_bytetrack__objecttracker__pb2.InitResponse.SerializeToString,
            ),
            'UpdateTracks': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTracks,
                    request_deserializer=proto_dot_bytetrack__objecttracker__pb2.FrameDetections.FromString,
                    response_serializer=proto_dot_bytetrack__objecttracker__pb2.TracksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tracker.TrackerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tracker.TrackerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrackerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitTracker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.TrackerService/InitTracker',
            proto_dot_bytetrack__objecttracker__pb2.TrackerParams.SerializeToString,
            proto_dot_bytetrack__objecttracker__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTracks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tracker.TrackerService/UpdateTracks',
            proto_dot_bytetrack__objecttracker__pb2.FrameDetections.SerializeToString,
            proto_dot_bytetrack__objecttracker__pb2.TracksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
