# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bytetrack_objecttracker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bytetrack_objecttracker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62ytetrack_objecttracker.proto\x12\x07tracker\"J\n\tDetection\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02y1\x18\x02 \x01(\x02\x12\n\n\x02x2\x18\x03 \x01(\x02\x12\n\n\x02y2\x18\x04 \x01(\x02\x12\r\n\x05score\x18\x05 \x01(\x02\"i\n\x0f\x46rameDetections\x12 \n\x04\x64\x65ts\x18\x01 \x03(\x0b\x32\x12.tracker.Detection\x12\x11\n\timg_width\x18\x02 \x01(\x05\x12\x12\n\nimg_height\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\"C\n\x05Track\x12\n\n\x02id\x18\x01 \x01(\x05\x12\n\n\x02x1\x18\x02 \x01(\x02\x12\n\n\x02y1\x18\x03 \x01(\x02\x12\n\n\x02x2\x18\x04 \x01(\x02\x12\n\n\x02y2\x18\x05 \x01(\x02\"0\n\x0eTracksResponse\x12\x1e\n\x06tracks\x18\x01 \x03(\x0b\x32\x0e.tracker.Track\"f\n\rTrackerParams\x12\x14\n\x0ctrack_thresh\x18\x01 \x01(\x02\x12\x13\n\x0bhigh_thresh\x18\x02 \x01(\x02\x12\x14\n\x0cmatch_thresh\x18\x03 \x01(\x02\x12\x14\n\x0ctrack_buffer\x18\x04 \x01(\x05\"\x1a\n\x0cInitResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\x91\x01\n\x0eTrackerService\x12<\n\x0bInitTracker\x12\x16.tracker.TrackerParams\x1a\x15.tracker.InitResponse\x12\x41\n\x0cUpdateTracks\x12\x18.tracker.FrameDetections\x1a\x17.tracker.TracksResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bytetrack_objecttracker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETECTION']._serialized_start=42
  _globals['_DETECTION']._serialized_end=116
  _globals['_FRAMEDETECTIONS']._serialized_start=118
  _globals['_FRAMEDETECTIONS']._serialized_end=223
  _globals['_TRACK']._serialized_start=225
  _globals['_TRACK']._serialized_end=292
  _globals['_TRACKSRESPONSE']._serialized_start=294
  _globals['_TRACKSRESPONSE']._serialized_end=342
  _globals['_TRACKERPARAMS']._serialized_start=344
  _globals['_TRACKERPARAMS']._serialized_end=446
  _globals['_INITRESPONSE']._serialized_start=448
  _globals['_INITRESPONSE']._serialized_end=474
  _globals['_TRACKERSERVICE']._serialized_start=477
  _globals['_TRACKERSERVICE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
